### ISSUE TITLE
Create user authentication

### ISSUE THREAD

**Issue by cesandoval** [cesandoval/PaintingWithData_Riyadh#1]
Create models for users, and the queries to save and authenticate them.

**Comment by cesandoval** [comment]
Now that the DB is created, resources to create the user can be found:
[here](https://scotch.io/tutorials/easy-node-authentication-setup-and-local) and [here](https://scotch.io/tutorials/authenticate-a-node-js-api-with-json-web-tokens)

**Comment by cesandoval** [comment]
I migrated the DB to Postgres from Mongo. Users can be created, but the login is not working. Additionally, I haven't been able to install bcrypt to encrypt the user info, due to bcrypt windows compatibility issues.

**Comment by cesandoval** [comment]
Update:
The signup view is not saving any users in the DB. Potentially might have to do with [this](https://github.com/cesandoval/PaintingWithData_Riyadh/blob/master/app/controllers/signupController.js#L35).

Since users are not being saved in the DB, it is not possible to authenticate them.

EDIT:
The DB was being rewritten every time the code ran because the model sync was [forced](https://github.com/cesandoval/PaintingWithData_Riyadh/blob/master/app/controllers/signupController.js#L37). 

Apparently I fixed the signup issues and now we should handle the successful login. Maybe redirect to the index page, but being authenticated. A good place to handle all of that might be [here](https://github.com/cesandoval/PaintingWithData_Riyadh/blob/master/app/routers/appRouter.js#L89). 

We have to also figure out how to hash the password and username. I was trying [this](https://github.com/cesandoval/PaintingWithData_Riyadh/blob/master/app/controllers/signupController.js#L27), but am having troubles installing the libraries on windows.

If all seems to work we can move to #3 .

**Comment by Tariq60** [comment]
Hashing added to signup Controller and seems to work. Kindly check and confirm. If so, maybe we can close this issue

**Comment by cesandoval** [comment]
Added async to the password hashing, and changed the models to accept more bits per column. Modified the login controller to use the hashing verify function.
