### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by cesandoval** [cesandoval/PaintingWithData_Riyadh#100]
- [x] Add 'Map Screenshot' text next to the icon.
- [x] Open a save to dialog box when saving a screenshot

**Comment by ooookai** [comment]
- [x] change image format from JPEG to PNG.

**Comment by cesandoval** [comment]
closed [here](https://github.com/cesandoval/PaintingWithData_Riyadh/commit/8d2dc25b8a3ea2c53dcbc44b5f9b0187d2398724)
