### ISSUE TITLE
VPL node names

### ISSUE THREAD

**Issue by cesandoval** [cesandoval/PaintingWithData_Riyadh#101]
The node names do not correspond to the VPL nodes when added. Add _1... etc to the node names from the start.

**Comment by cesandoval** [comment]
Also, when the nodes are originally added, the color picker is black by default and changes once you move them around.

**Comment by ooookai** [comment]
node color picker and name is not prepared when the node be added and rendered.

**Comment by cesandoval** [comment]
[Closed](https://github.com/cesandoval/PaintingWithData_Riyadh/commit/de337716f88f300ced120b73b2ba68d33eeee369)
