### ISSUE TITLE
function for node input

### ISSUE THREAD

**Issue by cesandoval** [cesandoval/PaintingWithData_Riyadh#105]
create a function that gets triggered when the inputs of the other nodes are plugged into the inputs. 

the function should return:

- [ ] the name of the current node
- [ ] the name of the node(s) plugged into the node

**Comment by ooookai** [comment]
These not work. Start [VPL Refactoring](https://github.com/cesandoval/PaintingWithData_Riyadh/tree/refactor-vpl).
