### ISSUE TITLE
Unit tests for front-end

### ISSUE THREAD

**Issue by cesandoval** [cesandoval/PaintingWithData_Riyadh#107]
With [Jest](https://facebook.github.io/jest/)

**Comment by ooookai** [comment]
Jest (https://facebook.github.io/jest/)
🃏 Delightful JavaScript Testing
*by Facebook*

**Comment by cesandoval** [comment]
@ooookai : is this closed with [this branch](https://github.com/cesandoval/PaintingWithData_Riyadh/tree/setup-lint-prettier)?

**Comment by cesandoval** [comment]
working now
