### ISSUE TITLE
VPL bugs

### ISSUE THREAD

**Issue by cesandoval** [cesandoval/PaintingWithData_Riyadh#112]
- [x] application too slow when reloading the base map
- [ ] layer nodes get turned on when plugged into a node
- [x] addition node is missing 
- [x] application should not start with the VPL open, it should start with the pcoords and map instead.
- [x] opacity and smoothing sliders are disabled
- [x] no initial mock data loaded for now (until we figure out how to do it with the ui)

**Comment by ooookai** [comment]
fixed
