### ISSUE TITLE
Description of Node on Hover

### ISSUE THREAD

**Issue by cesandoval** [cesandoval/PaintingWithData_Riyadh#141]
When we hover over a node, we should display information about the node:

- [ ] Types of inputs it takes
- [ ] Types of outputs it gives
- [x] What the node does

**Comment by ooookai** [comment]
what's the types?

**Comment by cesandoval** [comment]
You are right, perhaps at this point all of the input types are matrices of numbers generated from the nodes. Eventually when we add other node types, like sliders, single numbers, or booleans, this can become more explicit.

**Comment by cesandoval** [comment]
Closed #155
