### ISSUE TITLE
Refactor: Redux States.sidebar check

### ISSUE THREAD

**Issue by ooookai** [cesandoval/PaintingWithData_Riyadh#162]
## Discussion

According to our previous discussion, We want to simplify/integrate the redux states, and we decide to get rid of the `states.sidebar`. So I am going to merge them to the other states if we need it.

However, now we add the datasets(layers) data to the `states.sidebar.layers`, and I found we used it for several things. I can try refactor them all but I think you might need to check them all before I start if you want.

Can I use `states.datasets` or something else, to replace `states.sidebar.layers`? 

And the datasets(layers) should be stored as an Object instead of an Array because it should have an unique key.

In the following situations, we might still need the `states.datasets` i think, right?

---

## Please check these code which we've used the `states.sidebar`

1. Generate the geometries at the first time.
https://github.com/cesandoval/PaintingWithData_Riyadh/blob/fba74f03fd6c2d8b336e197a29b2c88082ad0aaa/private/jsx/map/map.js#L29

2. Initialize the parallel coordinates
https://github.com/cesandoval/PaintingWithData_Riyadh/blob/fba74f03fd6c2d8b336e197a29b2c88082ad0aaa/private/jsx/pcoords/pcoords.js#L32

3. Render the sidebar
https://github.com/cesandoval/PaintingWithData_Riyadh/blob/fba74f03fd6c2d8b336e197a29b2c88082ad0aaa/private/jsx/sidebar/layers.js#L168

4. A part of KNN slider computing?
https://github.com/cesandoval/PaintingWithData_Riyadh/blob/fba74f03fd6c2d8b336e197a29b2c88082ad0aaa/private/jsx/sidebar/knnSlider.js#L17

5. For geometry default value
https://github.com/cesandoval/PaintingWithData_Riyadh/blob/fba74f03fd6c2d8b336e197a29b2c88082ad0aaa/private/jsx/vprog/rVpl.js#L817

6. A parameter for geometry computing?
https://github.com/cesandoval/PaintingWithData_Riyadh/blob/fba74f03fd6c2d8b336e197a29b2c88082ad0aaa/private/jsx/vprog/rVpl.js#L726

7. Add datasets node to vpl
https://github.com/cesandoval/PaintingWithData_Riyadh/blob/fba74f03fd6c2d8b336e197a29b2c88082ad0aaa/private/jsx/vprog/rVpl.js#L80

8. Export SVG function
https://github.com/cesandoval/PaintingWithData_Riyadh/blob/fba74f03fd6c2d8b336e197a29b2c88082ad0aaa/private/jsx/map/map.js#L74

**Comment by cesandoval** [comment]
I agree, the datasets should have a key instead of being an array. We can definitely use `states.datasets` for **1, 2, 3, 4,7, and 8**. For **5 and 6**, we need to add a `geojson.minMax` and a `allIndices` property to `states.datasets`

**Comment by ooookai** [comment]
- [X] **1**: use `!_.isEmpty(newProps.layers)`
- [X] **2**: use `!_.isEmpty(nprops.layers)`
- [X] **3**: use `Object.entries(layers)`
- [X] **4**: remove `this.layers`
- [X] **5**: use `this.newProps.datasets.minMax`
- [X] **6**: use `this.newProps.datasets.allIndices`
- [X] **7**: use `Object.values(layers)` and `!_.isEmpty(layers)`
- [X] **8**: use `_.first(this.props.layers)`

> use `!_.isEmpty(layers)` to checks if object is an empty.
> replace all `sidebar.layers` to `datasets.layers`, or remove it if it's useless.

**Comment by ooookai** [comment]
closed #167
