### ISSUE TITLE
Display Public projects

### ISSUE THREAD

**Issue by ooookai** [cesandoval/PaintingWithData_Riyadh#274]
https://github.com/cesandoval/PaintingWithData_Riyadh/blob/01d3da39ae8ec95ec357365456eee6b02c2b9370/app/routers/appRouter.js#L83

@cesandoval 
confirm `isAuthenticated`
You want users to sign in, to see public projects, right?

**Comment by cesandoval** [comment]
@ooookai I think it might actually be good to have it open to everyone without being authenticated. The issue is that we need to show the datasets and projects too when you are not authenticated. I think removing `isAuthenticated` makes sense.

**Comment by cesandoval** [comment]
closed https://github.com/cesandoval/PaintingWithData_Riyadh/blob/publicProjects/app/routers/appRouter.js#L83
