### ISSUE TITLE
z fighting at high levels of zoom

### ISSUE THREAD

**Issue by aluo-x** [cesandoval/PaintingWithData_Riyadh#28]
Z fighting appears when the zoom level is high. 
See example: https://i.imgur.com/E4nYPOD.png

HW info:

OpenGL version string: 3.0 Mesa 17.1.0-devel - padoka PPA

Chrome Browser info:

Data exported	2/1/2017, 4:13:18 PM

Chrome version	Chrome/56.0.2924.76

Operating system	Linux 4.9.3-040903-generic

Software rendering list version	0

Driver bug list version	9.24

ANGLE commit id	555009cefe4c

2D graphics backend	Skia/56 bf2d9e02d58ea01f1c239f7e2fc024cba140ccb1

GL_VENDOR	Intel Open Source Technology Center

GL_RENDERER	Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2)`

**Comment by cesandoval** [comment]
Fixed [here](https://github.com/cesandoval/PaintingWithData_Riyadh/commit/edc433d70fd69561a28da389bec1ccad132e9665)
