### ISSUE TITLE
Worker for Datafiles to Datalayers

### ISSUE THREAD

**Issue by cesandoval** [cesandoval/PaintingWithData_Riyadh#35]
Implement it, just like Datavoxels

**Comment by cesandoval** [comment]
fixed [here](https://github.com/cesandoval/PaintingWithData_Riyadh/tree/uploadViewerWorker) the issue with kue. Had to do with circular structures on the JSON that was being passed to the worker. 

@yefrem96 can you add a function that sends an email telling the user that his file has been uploaded once the worker is done? Then we can merge this branch to master.

**Comment by yefrem96** [comment]
Yeah sure, nice job finding the issue!

**Comment by cesandoval** [comment]
closed in #72 . Stealing your glory, and closing the issue here!
