### ISSUE TITLE
Data Explorer Aggregates Layers with Same Attribute Name

### ISSUE THREAD

**Issue by cortnik** [cesandoval/PaintingWithData_Riyadh#65]
For example, I have a voxel project with 4 Twitter layers (corresponding to different times of day) and an accident layer. Rather than showing 5 layers in the chart, the chart shows 2 layers. It looks like it is aggregating data layers with like attribute names (count1). 

http://paintingwithdata.mit.edu/app/10

**Comment by cesandoval** [comment]
Solved [here](https://github.com/cesandoval/PaintingWithData_Riyadh/commit/d2e9ffc726df69373f5dea18495bc6b2e812b1df). Now we name the axis in the data explorer by adding the layer name as a prefix.
