### ISSUE TITLE
Create an SVG, SHP, and JSON export function. Save files and all states.

### ISSUE THREAD

**Issue by ooookai** [cesandoval/PaintingWithData_Riyadh#85]
### SVG
- Layers
  1. map background ?
  2. Voxel layer
  3. text information
    - property of layer (e.g.  color, name)
    - query
    - vpl

- voxel element
  - relative position
  - color
  - value ?

### JSON
- Export all the layers as a geoJSON layer collection

### SHP
- Create a shapefile per layer
  1. This might have to happen with PostGIS? 
  2. Other libraries might translate the coordinates and values into SHP files
  3. The geometry would be a point per voxel with the attributes in the DBF file

**Comment by ooookai** [comment]
**Priority**
SVG > SHP > JSON

**Comment by cesandoval** [comment]
Export SHP is missing. Might have to do it on the backend

**Comment by cesandoval** [comment]
Close #189
