### ISSUE TITLE
Add new layer to sidebar when computing with VPL

### ISSUE THREAD

**Issue by cesandoval** [cesandoval/PaintingWithData_Riyadh#86]
Every time we combine layers with a visual programming language, we are adding the layer to the three js buffer geometry, but we are not adding the layer information to the sidebar. We should create a new layer object to add to the sidebar. When [this](https://github.com/cesandoval/PaintingWithData_Riyadh/blob/master/private/jsx/vprog/Vpl.js#L863) function is called, we also need to use the reducer that adds the layer to the side bar and to the state.

**Comment by ooookai** [comment]
**Questions:**

1. Does the new layer can be use with VPL again ?  **Yes**
2. Does the new layer would be control by parallel-coordinates too ? **??**
3. Why each layer needs 2 colors option? **??**
4. Each layer has own opacity slider layer? **??**

**Comment by cesandoval** [comment]
[Closed](09b1ae7a7eb5b74c61e17b8c7d8aacadb2b144d0)
