### ISSUE TITLE
Names for new layers created from VPL

### ISSUE THREAD

**Issue by cesandoval** [cesandoval/PaintingWithData_Riyadh#87]
When a new layer is created with the VPL #86 , assign a new name to the newly created layer. The name should be a combination of both source names, and the operation of the node. If the name already exists, add a number as a suffix.

**Comment by ooookai** [comment]
Try to design a new side bar layers by prototype, and then start coding.

**Comment by cesandoval** [comment]
[Closed](09b1ae7a7eb5b74c61e17b8c7d8aacadb2b144d0)
