### ISSUE TITLE
Zoom in and out and move the VPL canvas

### ISSUE THREAD

**Issue by cesandoval** [cesandoval/PaintingWithData_Riyadh#88]
Add functionality to zoom in and out from the VPL canvas and drag it around too

**Comment by ooookai** [comment]
Zoom in/out for the VPL space.

**Comment by cesandoval** [comment]
Seems like zooming in and out is not possible now, so we will look at panning instead

**Comment by cesandoval** [comment]
Closed [here](https://github.com/cesandoval/PaintingWithData_Riyadh/pull/127)
